apiVersion: v1
kind: Service
metadata:
  name: blackjack
  namespace: blackjack
spec:
  selector:
    app: blackjack
    type: test
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011