apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tomer-lab4
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shlomobarzili/lab4-backend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5050
          protocol: TCP
        env:
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: MONGO_INITDB_ROOT_PASSWORD
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: MONGO_INITDB_ROOT_USERNAME  
          - name: MONGO_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: MONGO_DB_HOST
     
