apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: tomer-lab4
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31251