apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tomer-lab4
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shlomobarzili/lab4-react-pronted:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP

        env:
          - name: REACT_APP_API_URL
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: REACT_APP_API_URL