apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization-deployment-all
  namespace: tomer-lab4
  labels:
    argocd.argoproj.io/instance: argo-cd
resources:
  - configmap.yml
  - mongo-deployment.yml
  - mongo-svc.yml
  - backend-deployment.yml
  - backend-svc.yml
  - frontend-deployment.yml
  - frontend-svc.yml