apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: tomer-lab4
spec:
  selector:
    app : mongo
  type: ClusterIP  
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      