version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend  # Adjust this path based on your project structure
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5050
      - WATCHPACK_POLLING=true  # Enable hot reload on Windows/Docker
      - WDS_SOCKET_PORT=0  # Required for hot reload in container
    volumes:
      - ./frontend:/app  # For hot reloading
      - /app/node_modules  # Prevents overwriting node_modules in container
    depends_on:
      - web

  web:
    build: 
      context: ./backend  # Adjust this path
    ports:
      - "5050:5050"
    environment:
      - MONGO_DB_USERNAME=root
      - MONGO_DB_PASSWORD=example
      - MONGO_DB_HOST=mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # volumes:
    #   - mongodb_data:/data/db

# volumes:
#   mongodb_data:

networks:
  default:
    driver: bridge