apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: lab4
  labels:
    app: mongodb-lab4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-lab4
  template:
    metadata:
      labels:
        app: mongodb-lab4
    spec:
      containers:
      - name: mongodb
        image: shlomobarzili/lab4-mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: variables-app-sean-shlomo
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: variables-app-sean-shlomo
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: variables-app-sean-shlomo
              key: MONGO_DB_HOST
      #   volumeMounts:
      #   - name: volume
      #     mountPath: /usr/local/apache2/htdocs
      # volumes:
      # - name: volume
      #   persistentVolumeClaim:
      #     claimName: pvc0003
