apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomizion-deployment-all
  namespace: lab4
  labels:
    argocd.argoproj.io/instance: argo-cd
resources:
  - configmap.yml
#  - pvc.yml
  - db-deploment.yml
  - db-svc.yml
  - backend-deployment-svc.yml
  - backend.svc.yml
  - fronted-deployment-svc.yml
  - fronted.svc.yml
  - ingress.yml