# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pvc0003
#   namespace: lab4
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /home/docker/src

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc0003
#   namespace: lab4
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
