apiVersion: v1
kind: Service
metadata:
  name: guest-number-game-service
spec:
  selector:
    app: guest-number-game
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30006


# apiVersion: v1
# kind: Service
# metadata:
#   name: guest-number-game-service
# spec:
#   selector:
#     app: guest-number-game
#   type: ClusterIP 
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
     # nodePort: 30010


# apiVersion: v1
# kind: Service
# metadata:
#   name: guest-number-game-service
# spec:
#   selector:
#     app:  guest-number-game
#   type: LoadBalancer  
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       nodePort: 30006
#   # externalIPs:
  #   - 10.0.11.10
  #   - 192.168.49.2
